### PR TITLE
refactor react-native-init

### PR DESCRIPTION
**Pull request by silentcloud**
#29 

还需要改一下 https://github.com/yiminghe/react-native-index-page，等改完

### CODE REVIEW

**Comment by silentcloud** [comment]
ref https://github.com/yiminghe/react-native-index-page/pull/2

**Comment by silentcloud** [comment]
done  cc @yiminghe

**Comment by yiminghe** [comment]
把这些 tar 放到 cdn 每次下载吧. @silentcloud

**Comment by silentcloud** [comment]
@yiminghe  这几个 tar.gz 也不是很大。那我放 cdn 去

**Pull request merged**
